### ISSUE TITLE
"Don't count" as checkbox, not menu item

### ISSUE THREAD

**Issue by ghost** [mami-project/pto-postgres#38]
Don’t have “don’t count” as item in drop-down menu, instead have it as checkbox. Rationale: too easy to miss; might give the impression that one always needs to count.

**Comment by mirjak** [comment]
Actually, we decided to remove the 'don't count' completely; I didn't this in my branch. We have another idea how to retrieve observation result set but let's first fix the other issues.

**Comment by mirjak** [comment]
See #64
