### ISSUE TITLE
Table should mimic graph 1:1 and vice versa

### ISSUE THREAD

**Issue by ghost** [mami-project/pto-postgres#42]
If the query specifies “group by”, then show the table grouped by that criterion, do not show every condition in a single row. This means removing the “Count” column. Instead, put all conditions applying to that grouping criterion in the “condition” column, with their counts, e.g., “ecn.connectivity.works(10), ecn.connectivity.broken(4)”.

**Comment by FMNSSun** [comment]
partially done.

**Comment by mirjak** [comment]
What's missing here? The table is actually now fine as it is!

**Comment by FMNSSun** [comment]
then let's close this :).
