### ISSUE TITLE
Time span estimate in result table

### ISSUE THREAD

**Issue by ghost** [mami-project/pto-postgres#43]
In that table, add two columns “From” and “To” giving a reasonable estimate of the tie spans for the relevant observations. (May not be done by 1 March. May not be doable at all in reasonable time. Reason is that queries of a `IF NOT EXISTS...` nature may touch an unknown number of rows)

**Comment by FMNSSun** [comment]
Can't be done. If you aggregate you have no timestamps anyway. What's the use case for this?

**Comment by mirjak** [comment]
Yes, we need to discuss this further. Maybe just leave the issue open for later. The use case is if you have a query and you want to further refine this for generate a next query, the time would be an interesting piece of meta data.

**Comment by mirjak** [comment]
Related to #58

**Comment by ghost** [comment]
WONTFIX
