### ISSUE TITLE
Conditions counts as graph in addition to numeric counts

### ISSUE THREAD

**Issue by ghost** [mami-project/pto-postgres#45]
The graph legend currently shows the condition counts next to the condition names. These counts should themselves be shown as a graph INSTEAD.

**Comment by ghost** [comment]
I think this is of questionable utility

**Comment by mirjak** [comment]
I thinks this depends on the graph... let's keep this on the list for later and fix the other issues first.

**Comment by ghost** [comment]
WONTFIX
