### ISSUE TITLE
Simple question graphs on main page instead of "Get answers" menu

### ISSUE THREAD

**Issue by ghost** [mami-project/pto-postgres#47]
Instead of having a page “get answers to questions” linked from the main page, put graphs corresponding to ALL these questions directly on the main page. Make the graphs clickable so that they link to either the (now hidden) “Get answers” page or to the “make query” page, with correct values already filled in. Rationale: The “get answers” graphs exist to get people to try to experiment with queries by showing them interesting queries for them to play with.

**Comment by ghost** [comment]
I think this is of questionable utility and will clutter the main page

**Comment by FMNSSun** [comment]
embed them as raw images?

**Comment by mirjak** [comment]
There also need to go some front matter and explanations on the main page. I'll come up with some text as soon as the graph are there.

**Comment by mirjak** [comment]
yes raw images are okay as long as they link to the result page

**Comment by mirjak** [comment]
Please add those graphs soon. Than I can also add some more explanation text to the front page...

**Comment by FMNSSun** [comment]
done. there are svgs on the frontpage now.
