### ISSUE TITLE
Useful headers for graphs

### ISSUE THREAD

**Issue by ghost** [mami-project/pto-postgres#50]
Make useful headers for graphs, for example by translating the IQL back into more or less natural language, or by taking the parameters from the query interface and making an english sentence from them. Rationale: it is easier to understand what you are seeing if you have a description. (This description is partially there already.)

**Comment by FMNSSun** [comment]
define useful. the whole english translation spans multiple lines and I think is unsuited for graph headers.

**Comment by ghost** [comment]
WONTFIX
