### ISSUE TITLE
Enable exploration workflow

### ISSUE THREAD

**Issue by ghost** [mami-project/pto-postgres#51]
When showing the result of the query, have the form with the query parameters on top of the page, so that users can easily modify a query without having to hit the “back” button. Rationale: This supports an
exploration workflow.

**Comment by FMNSSun** [comment]
That could be tricky as you have to again filter out what was entered based on the IQl query. Which is kinda messy :D.

**Comment by FMNSSun** [comment]
although. maybe not that messy if we just integrate the results page into the qui page. I'll look at this.

**Comment by mirjak** [comment]
Yes, that's the idea. Thanks!

**Comment by FMNSSun** [comment]
I've pushed a version. Probably needs some minor/major tweaks.

**Comment by FMNSSun** [comment]
closed.
