### ISSUE TITLE
Add path selector and radio button for endpoint types

### ISSUE THREAD

**Issue by ghost** [mami-project/pto-postgres#52]
The query interface should have the option to specify the source or destination of a path, and the UI should contain a radio button, specifying “IP address”, “AS number” or “pseudonym”.

**Comment by ghost** [comment]
Since paths are arrays of text anyway, the semantics of what the user enters doesn’t matter, so this radio button will be inoperative. Having inoperative UI elements is _very_ bad style.

**Comment by FMNSSun** [comment]
I think the idea would be to do "input verification" depending on what was selected.

**Comment by mirjak** [comment]
The idea is mainly to give the user some hits what kind of input types exist. I can care about this, I think. This is not about function, only about representation.

**Comment by mirjak** [comment]
More or less done.
