### ISSUE TITLE
It takes too load until something happen when you press 'run query'...

### ISSUE THREAD

**Issue by mirjak** [mami-project/pto-postgres#59]
... and therefore it happens that you press 'run query' multiple time... we need some kind of immediate feedback. Maybe we can just open a box with a message. The good thing is: given that we basically don't have any free text fields anymore (e.g. for the time stamp). It is not possible anymore to create an invalid query with the qui and therefore we probably don't need any of the error messages anymore.

**Comment by FMNSSun** [comment]
Yes, we need some kind of visual feedback like one of those spinning gifs.

**Comment by mirjak** [comment]
I also discussed with Stephan that we should probably wait at least 10s, maybe more, before we tell the user to come back later. And if we tell this user to come back later, maybe we can ask the user for an email address and notify the user when the results are ready. 

Does it have already an own issue (that i missed) or got this a little lost.

I think that is the most important feature we want to have (beside the smaller nits we should try to fix before March 1)

**Comment by FMNSSun** [comment]
queries completing in 10s are rather unrealistic based on time a query takes which is easily in the minutes at least most raning about 1h. Anyway now the button is disabled until the response is there.

**Comment by mirjak** [comment]
I had the feeling that a query often either takes a few second or much longer. At least those that only take a few seconds should be displayed immediately (Whichout this message 'come back in an hour...)

**Comment by FMNSSun** [comment]
I think we can close this for now. The UI already does the following:
- Submit the query, if result already present render them
- If result not present, wait 10s and then try again.

**Comment by mirjak** [comment]
Would it be possible to have try every second for 10s?
