### ISSUE TITLE
Completion time in query queue should only include the precessing time and not the time it was waiting in the queue (or both separately)

### ISSUE THREAD

**Issue by mirjak** [mami-project/pto-postgres#68]
Or what does it actually show?

**Comment by FMNSSun** [comment]
completion time does not include waiting time.

**Comment by mirjak** [comment]
Okay, then we should probably try to optimize the processing time again. Do you know why it takes so long? Is it the query/queries itself or some sorting or some postprocessing? Maybe we need to re-organize the tables accordingly, e.g. one table per condition groups...?
