### ISSUE TITLE
query queue should show more entries

### ISSUE THREAD

**Issue by mirjak** [mami-project/pto-postgres#73]
Can we increase the number of displayed entries for now? Later on we probably want to have multiple pages which e.g. 25 entries per page to browse thought the whole query queue.

**Comment by FMNSSun** [comment]
increased the limit for now.

**Comment by FMNSSun** [comment]
limit increased, empty results are hidden.

**Comment by mirjak** [comment]
empty results should only be hidden if you didn't give an id to the user otherwise that would be confusing

**Comment by mirjak** [comment]
if an empty results is not hidden it doesn't have to be clickable though
