### ISSUE TITLE
observatory.mami-project.eu has an invalid certificate

### ISSUE THREAD

**Issue by britram** [mami-project/pto-postgres#76]
Since the ZHAW root cert doesn't show up in any non-ZHAW machine, attempts to access will cause a security exception. Access to PAPI via Javascript, in particular, will fail silently on Firefox and Chrome, which causes the observatory to simply appear broken.

We should use a Let'sEncrypt cert to protect access to observatory.mami-project.eu.

**Comment by ghost** [comment]
Certbot it is.
